### ISSUE TITLE
cores?

### ISSUE THREAD

**Issue by mcfaddenlab** [BenoitMorel/multi-raxml#54]
i am a little confused on how to optimize a pargenes run. 
I would like to run model test first, and then raxml. 
here is my command:
python pargenes.py -a mafft-nexus-internal-trimmed-gblocks-clean-75p-phylip -o pargenes-uce-75p-run1 -c 13 -d nt  -m  -b 100  --dry-run
and received the following info:
 Average number of taxa: 204
  Max number of taxa: 246
  Average number of sites: 243
  Max number of sites: 728
  Recommended number of cores: 1388

I only have 64 cores, and don't really want to use all of them as I have other processes running.

Any advice to optimize this and the time that it may take to test models, and run gene trees on ~400 genes? Or should I just use GTRG on all the gene trees?

**Comment by mcfaddenlab** [comment]
well, modeltest actually took no time at all. I am now getting this error:
Please advise. thanks!
0:40:45] end of parsing  modeltest results
Calling mpi-scheduler: mpiexec -n 13 /data/mcfadden/aquattrini/PROGRAMS/ParGenes/MPIScheduler/build/mpi-scheduler --split-scheduler /data/mcfadden/aquattrini/PROGRAMS/ParGenes/pargenes/../raxml-ng/bin/raxml-ng-mpi.so pargenes-uce-75p-run1/parse_run/parse_command.txt pargenes-uce-75p-run1/parse_run 0
Logs will be redirected to pargenes-uce-75p-run1/parse_run/logs.txt
  Average number of taxa: 204
  Max number of taxa: 246
  Average number of sites: 243
  Max number of sites: 728
  Recommended number of cores: 1388
[0:40:46] end of the second parsing step
Calling mpi-scheduler: mpiexec -n 13 /data/mcfadden/aquattrini/PROGRAMS/ParGenes/MPIScheduler/build/mpi-scheduler --split-scheduler /data/mcfadden/aquattrini/PROGRAMS/ParGenes/pargenes/../raxml-ng/bin/raxml-ng-mpi.so pargenes-uce-75p-run1/mlsearch_run/mlsearch_command.txt pargenes-uce-75p-run1/mlsearch_run 0
Logs will be redirected to pargenes-uce-75p-run1/mlsearch_run/logs.txt
[Error] mpi-scheduler execution failed with error code 1
[Error] Will now exit...
[Error] <type 'exceptions.RuntimeError'> mpi-scheduler  execution failed with error code 1

**Comment by BenoitMorel** [comment]
To reply to your first post:
the recommended number of cores is the number of cores you should not exceed (maybe I will update the message to make it clearer).

In your case, since, you have 64 cores, it's up to you: if you assign 26 cores, it will run 2 times faster than if you assign 13 cores. 

It's unfortunately impossible to know how long an analysis will take (because it does not only depend on the size of your alignments, but also on the number of iterations raxml needs to converge). 

One interesting point for you: you can stop your analysis at any time and restart it with the exact same command line but with a different number of cores and `--continue` (see https://github.com/BenoitMorel/ParGenes/wiki/Checkpointing), without losing the previous results.

For your second post, see my answer on the raxml google group.
