### ISSUE TITLE
Tags for newer versions

### ISSUE THREAD

**Issue by tardigradus** [BenoitMorel/multi-raxml#61]
Would it be possible to create release tags for newer versions than 1.0.1?

**Comment by BenoitMorel** [comment]
Hi Tardigradus,

Yes, sure. I will do that this week, after upgrading the last version of raxml-ng and answering a few requests.

Benoit

**Comment by tardigradus** [comment]
OK, thanks!

Apropos RAxML-NG, have you considered unbundling ParGenes from its dependencies?  For instance, on our university HPC system we already have RAxML installed separately and can update it ourselves when a new version comes out.
I understand that you want to make your software easier to use for individual users, but for administrator such bundling of software can make life more complicated.  Perhaps it could be an install option, whether the bundled subprojects should be used or not.

**Comment by BenoitMorel** [comment]
I completely understand this installation/dependencies nightmare :-)
One issue is that for pargenes-mpi.py (instead of pargenes.py), we use a custom raxml-ng  build: we build raxml-ng as a dynamic library, and not as an executable. Thus you would either need to additionally install raxml-ng as a library on your cluster (there is one more cmake flag to add for that), or to use pargenes.py only.
But I can definitively add an option to specify your own raxml-ng command, and document the limitations I just described. If you still want it, can you open a separate issue?

**Comment by BenoitMorel** [comment]
I am closing this issue, since this conversation was moved to https://github.com/amkozlov/raxml-ng/issues/91
