### ISSUE TITLE
ASTRAL Test Failure

### ISSUE THREAD

**Issue by LilithMary** [BenoitMorel/multi-raxml#69]
Hi Benoit,

I hope you are well. 

I'm a part-time Informatician at Leicester University trying to set up ParGenes on a Linux server for biology students to use and I've encountered some issues during installation. 

After multiple tries each failing for a reason, I finally got everything installed and executed the run_tests.py code. Even though it passed the first 5 tests successfully, it failed on the sixth one (i.e. ASTRAL).
 
Would you please have a look at the report attached and help me solve the problem?

Kind regards,
Maryam

[report.txt](https://github.com/BenoitMorel/ParGenes/files/6547045/report.txt)

**Comment by BenoitMorel** [comment]
Dear Maryam,

Thanks for the report. Are you trying to install via bionconda or from the github repository? If you install with bioconda, are you trying to run `run_test.py` "manually" or was it run by the package installer?

In both cases, can you try this:
`cd /lustre/alice3/data/evassvis/software/anaconda3/ParGenes/ && ./checker.sh`

and if it works, run the following:
`rm -rf /lustre/alice3/data/evassvis/software/anaconda3/ParGenes/tests/tests_outputs/test_ml_search/pargenes-hpc && /lustre/alice3/data/evassvis/software/anaconda3/ParGenes/pargenes/pargenes-hpc.py -a /lustre/alice3/data/evassvis/software/anaconda3/ParGenes/tests/smalldata/fasta_files -o /lustre/alice3/data/evassvis/software/anaconda3/ParGenes/tests/tests_outputs/test_ml_search/pargenes-hpc -r /lustre/alice3/data/evassvis/software/anaconda3/ParGenes/tests/smalldata/raxml_global_options.txt -c 4 -s 3 -p 3 --scheduler split`

and copy-paste the logs from the console. This is the command called by the test script that fails, but I need the output printed in the console, because it might contain more logs than the `pargenes_log.txt` file or the report file.

Kind regards,
Benoit

**Comment by LilithMary** [comment]
Dear Benoit,

Many thanks for your prompt response.

I've tried to install via bioconda as well as directly via githup
repository but both have caused issues. I ran checker.sh and run_tests.py
code manually afterwards.

I just tried the first command you suggested and this is the output:

(pargenes_env_3) ***@***.*** ~]$ cd
/lustre/alice3/data/evassvis/software/anaconda3/ParGenes/ && ./checker.sh
Running checker.sh...
ERROR: pargenes/pargenes_binaries/raxml-ng-mpi.so does not exist


This is the content of pargenes_binaries directory:

(pargenes_env_3) ***@***.*** ParGenes]$ cd pargenes/pargenes_binaries/
(pargenes_env_3) ***@***.*** pargenes_binaries]$ ls
astral.jar  lib  modeltest-ng  mpi-scheduler  raxml-ng


Is *raxml-ng* the same as *raxml-ng-mpi.so* which it says is missing?
I'd very much appreciate your help with this and I look forward to hearing
from you.

Kind regards,
Maryam

**Comment by BenoitMorel** [comment]
Dear Maryam,

raxml-ng-mpi.so is not built when MPI is not installed or can't be found.
This does not result in an error in the installation process, but it makes
the *-hpc* tests fail.
If you can't install MPI, users can still use ParGenes, but ParGenes won't
be able to parallelize over distributed memory nodes (see also
https://github.com/BenoitMorel/ParGenes/wiki/Parallelization)

However, it shouldn't be an issue when installing with conda, because MPI
should be in the list of dependencies...

Let me know if this helps
Benoit

**Comment by LilithMary** [comment]
Dear Benoit,

Thank you very much for your helpful response! 

I installed MPI (using conda) and then ParGenes from GitHub (tried installing ParGenes with conda as well, it said there are conflicting dependencies, I assume with MPI since it was a fresh environment otherwise) and it passed all the tests successfully. 

I very much appreciate your help in setting this up and I'll get in touch again if any further issues arise in working with ParGenes.

Kind regards,
Maryam

**Comment by LilithMary** [comment]
Dear Benoit,

Thank you very much for your helpful response! 

I installed MPI (using conda) and then ParGenes from GitHub (tried installing ParGenes with conda as well, it said there are conflicting dependencies, I assume with MPI since it was a fresh environment otherwise) and it passed all the tests successfully. 

I very much appreciate your help in setting this up and I'll get in touch again if any further issues arise in working with ParGenes.

Kind regards,
Maryam

**Comment by BenoitMorel** [comment]
Dear Maryam,

Thank you for your feedback. I am glad that it worked. Don't hesitate to get in touch if you encounter any further issue.

Best,
Benoit
